<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_blocks',
		'title' => 'Blocks',
		'fields' => array (
			array (
				'key' => 'field_5453ab99edd81',
				'label' => 'Blocks',
				'name' => 'blocks',
				'type' => 'flexible_content',
				'layouts' => array (
					array (
						'label' => 'Landing',
						'name' => 'landing',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_547dc740f109a',
								'label' => 'Each Landing',
								'name' => 'each_landing',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_547dc75df109b',
										'label' => 'Title',
										'name' => 'title',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_547dc762f109c',
										'label' => 'Subtitle',
										'name' => 'subtitle',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_547dc768f109d',
										'label' => 'Size',
										'name' => 'size',
										'type' => 'radio',
										'column_width' => '',
										'choices' => array (
											'normal' => 'Normal',
											'large' => 'Large',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
									),
									array (
										'key' => 'field_547dc779f109e',
										'label' => 'Button?',
										'name' => 'button_exists',
										'type' => 'true_false',
										'column_width' => '',
										'message' => '',
										'default_value' => 0,
									),
									array (
										'key' => 'field_547dc788f109f',
										'label' => 'Button Color',
										'name' => 'button_color',
										'type' => 'radio',
										'conditional_logic' => array (
											'status' => 1,
											'rules' => array (
												array (
													'field' => 'field_547dc779f109e',
													'operator' => '==',
													'value' => '1',
												),
											),
											'allorany' => 'all',
										),
										'column_width' => '',
										'choices' => array (
											'orange' => 'Orange',
											'blue' => 'Blue',
											'yellow' => 'Yellow',
											'green-lt' => 'Light Green',
											'green' => 'Green',
											'grey-x-lt' => 'Extra Light Grey',
											'grey-lt' => 'Light Grey',
											'grey-dk' => 'Dark Grey',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
									),
									array (
										'key' => 'field_548f9c4eb15c9',
										'label' => 'Button Hover Color',
										'name' => 'button_hover_color',
										'type' => 'radio',
										'column_width' => '',
										'choices' => array (
											'orange' => 'Orange',
											'blue' => 'Blue',
											'yellow' => 'Yellow',
											'green-lt' => 'Light Green',
											'green' => 'Green',
											'grey-x-lt' => 'Extra Light Grey',
											'grey-lt' => 'Light Grey',
											'grey-dk' => 'Dark Grey',
											'white' => 'White',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
									),
									array (
										'key' => 'field_548868ac8a849',
										'label' => 'Button Text',
										'name' => 'button_text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_548b3fefea8e7',
										'label' => 'Custom Button Link',
										'name' => 'custom_button_link',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_547dc7c0f10a0',
										'label' => 'Button Link',
										'name' => 'button_link',
										'type' => 'page_link',
										'conditional_logic' => array (
											'status' => 1,
											'rules' => array (
												array (
													'field' => 'field_547dc779f109e',
													'operator' => '==',
													'value' => '1',
												),
											),
											'allorany' => 'all',
										),
										'column_width' => '',
										'post_type' => array (
											0 => 'all',
										),
										'allow_null' => 0,
										'multiple' => 0,
									),
									array (
										'key' => 'field_547dc856f10a5',
										'label' => 'Text Color',
										'name' => 'text_color',
										'type' => 'radio',
										'column_width' => '',
										'choices' => array (
											'dark' => 'Dark',
											'light' => 'Light',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
									),
									array (
										'key' => 'field_547dc7e3f10a1',
										'label' => 'Background Image',
										'name' => 'background_image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'url',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_547dc7f2f10a2',
										'label' => 'Jumpoff?',
										'name' => 'is_jumpoff',
										'type' => 'true_false',
										'column_width' => '',
										'message' => '',
										'default_value' => 0,
									),
									array (
										'key' => 'field_547dc818f10a3',
										'label' => 'Background Color',
										'name' => 'background_color',
										'type' => 'radio',
										'conditional_logic' => array (
											'status' => 1,
											'rules' => array (
												array (
													'field' => 'field_547dc7f2f10a2',
													'operator' => '==',
													'value' => '1',
												),
											),
											'allorany' => 'all',
										),
										'column_width' => '',
										'choices' => array (
											'orange' => 'Orange',
											'blue' => 'Blue',
											'blue-grey' => 'Blue/Grey',
											'yellow' => 'Yellow',
											'green-lt' => 'Light Green',
											'green' => 'Green',
											'grey-x-lt' => 'Extra Light Grey',
											'grey-lt' => 'Light Grey',
											'grey-dk' => 'Dark Grey',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
									),
									array (
										'key' => 'field_547dc831f10a4',
										'label' => 'Jumpoff Icon',
										'name' => 'jumpoff_icon',
										'type' => 'radio',
										'conditional_logic' => array (
											'status' => 1,
											'rules' => array (
												array (
													'field' => 'field_547dc7f2f10a2',
													'operator' => '==',
													'value' => '1',
												),
											),
											'allorany' => 'all',
										),
										'column_width' => '',
										'choices' => array (
											'graph' => 'Graph',
											'arrow' => 'Arrow',
											'burst' => 'Burst',
											'ruler' => 'Ruler',
											'finger-press' => 'Finger',
											'travel' => 'Travel',
											'telco' => 'Telco',
											'financial' => 'Financial',
											'auto' => 'Auto',
											'e-commerce' => 'E-commerce',
											'publisher' => 'Publisher',
											'audience-extension' => 'Audience Extension',
											'lightning' => 'Lightning',
											'smile' => 'Smile',
											'dialogue' => 'Dialogue',
											'magazine' => 'Magazine',
											'whitepaper' => 'Whitepaper',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Landing',
							),
						),
					),
					array (
						'label' => 'Content Block',
						'name' => 'content_block',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5453abbeedd82',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5453abc4edd83',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5453abcbedd84',
								'label' => 'Content',
								'name' => 'content',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_5453ac81edd85',
								'label' => 'Button?',
								'name' => 'button_exists',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_5453ac96edd86',
								'label' => 'Button Color',
								'name' => 'button_color',
								'type' => 'radio',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_5453ac81edd85',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'choices' => array (
									'orange' => 'Orange',
									'blue' => 'Blue',
									'yellow' => 'Yellow',
									'green-lt' => 'Light Green',
									'green' => 'Green',
									'grey-lt' => 'Light Grey',
									'grey-dk' => 'Dark Grey',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'grey-dk',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_5453ad02edd87',
								'label' => 'Button Text',
								'name' => 'button_text',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_5453ac81edd85',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5453ad2dedd88',
								'label' => 'Button Link',
								'name' => 'button_link',
								'type' => 'page_link',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_5453ac81edd85',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'post_type' => array (
									0 => 'all',
								),
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_5453b35c7f757',
								'label' => 'Slant',
								'name' => 'slant',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'block-angle-up' => 'Slant Up',
									'block-angle-down' => 'Slant Down',
									'block-angle-none' => 'No Slant',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_5453b3e19c8e7',
								'label' => 'Background Color',
								'name' => 'background_color',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'orange' => 'Orange',
									'blue' => 'Blue',
									'blue-grey' => 'Blue/Grey',
									'yellow' => 'Yellow',
									'green-lt' => 'Light Green',
									'green' => 'Green',
									'grey-x-lt' => 'Extra Light Grey',
									'grey-lt' => 'Light Grey',
									'grey-dk' => 'Dark Grey',
									'white' => 'White',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_548f9c223f8e7',
								'label' => 'Button Hover Color',
								'name' => 'button_hover_color',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'orange' => 'Orange',
									'blue' => 'Blue',
									'yellow' => 'Yellow',
									'green-lt' => 'Light Green',
									'green' => 'Green',
									'grey-x-lt' => 'Extra Light Grey',
									'grey-lt' => 'Light Grey',
									'grey-dk' => 'Dark Grey',
									'white' => 'White',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_5453b3fb9c8e8',
								'label' => 'Background Image',
								'name' => 'background_image',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_5453cc0110888',
								'label' => 'Text Dark?',
								'name' => 'text_dark',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 1,
							),
							array (
								'key' => 'field_5453ba82c34b3',
								'label' => 'Video?',
								'name' => 'video_exists',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_5453baa2c34b4',
								'label' => 'Video Link',
								'name' => 'video_link',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_5453ba82c34b3',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5453c4a4e2f38',
								'label' => 'Icons?',
								'name' => 'icons_exist',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_5460f4a0d2c01',
								'label' => 'Icons',
								'name' => 'icons',
								'type' => 'repeater',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_5453c4a4e2f38',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_5460f4bed2c02',
										'label' => 'Icon',
										'name' => 'icon',
										'type' => 'radio',
										'column_width' => '',
										'choices' => array (
											'graph' => 'Graph',
											'arrow' => 'Arrow',
											'burst' => 'Burst',
											'ruler' => 'Ruler',
											'finger-press' => 'Finger',
											'travel' => 'Travel',
											'telco' => 'Telco',
											'financial' => 'Financial',
											'auto' => 'Auto',
											'e-commerce' => 'E-commerce',
											'publisher' => 'Publisher',
											'audience-extension' => 'Audience Extension',
											'lightning' => 'Lightning',
											'smile' => 'Smile',
											'dialogue' => 'Dialogue',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
									),
									array (
										'key' => 'field_5460f95a6b44e',
										'label' => 'Icon Color',
										'name' => 'icon_color',
										'type' => 'radio',
										'column_width' => '',
										'choices' => array (
											'orange' => 'Orange',
											'blue' => 'Blue',
											'yellow' => 'Yellow',
											'green-lt' => 'Light Green',
											'green' => 'Green',
											'grey-x-lt' => 'Extra Light Grey',
											'grey-lt' => 'Light Grey',
											'grey-dk' => 'Dark Grey',
											'white' => 'White',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
									),
									array (
										'key' => 'field_5460f4ebd2c03',
										'label' => 'Title',
										'name' => 'title',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_5460f4f2d2c04',
										'label' => 'Content',
										'name' => 'content',
										'type' => 'textarea',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => '',
										'formatting' => 'html',
									),
									array (
										'key' => 'field_5460f7696f4f3',
										'label' => 'Page Link',
										'name' => 'page_link',
										'type' => 'page_link',
										'column_width' => '',
										'post_type' => array (
											0 => 'all',
										),
										'allow_null' => 0,
										'multiple' => 0,
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Icon',
							),
							array (
								'key' => 'field_5460dbfe05fe2',
								'label' => 'Jumpoff Images?',
								'name' => 'jumpoff_images_exist',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_5460da5a05fe0',
								'label' => 'Jumpoff Images',
								'name' => 'jumpoff_images',
								'type' => 'repeater',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_5460dbfe05fe2',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_5460da7005fe1',
										'label' => 'Image',
										'name' => 'image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'url',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Row',
							),
							array (
								'key' => 'field_5487329508fb8',
								'label' => 'Sidebar?',
								'name' => 'is_sidebar',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_5487391626067',
								'label' => 'Sidebar Media Type',
								'name' => 'sidebar_media_type',
								'type' => 'radio',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_5487329508fb8',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'choices' => array (
									'none' => 'None',
									'image' => 'Image',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_5487393a26068',
								'label' => 'Sidebar Media',
								'name' => 'sidebar_media',
								'type' => 'image',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_5487329508fb8',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'save_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_5487395926069',
								'label' => 'Sidebar Media Caption',
								'name' => 'sidebar_media_caption',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_5487329508fb8',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_548732a508fb9',
								'label' => 'Sidebar Assets',
								'name' => 'sidebar',
								'type' => 'repeater',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_5487329508fb8',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_548732d408fba',
										'label' => 'Name',
										'name' => 'name',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_548732e408fbb',
										'label' => 'Link',
										'name' => 'link',
										'type' => 'page_link',
										'column_width' => '',
										'post_type' => array (
											0 => 'all',
										),
										'allow_null' => 0,
										'multiple' => 0,
									),
									array (
										'key' => 'field_54949c3f497a3',
										'label' => 'Custom Link',
										'name' => 'custom_link',
										'type' => 'text',
										'instructions' => 'Custom Link will always override the Page Link',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Asset',
							),
							array (
								'key' => 'field_5501ab74da58b',
								'label' => 'Add Extra Height?',
								'name' => 'add_extra_height',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
						),
					),
					array (
						'label' => 'Video Block',
						'name' => 'video_block',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5501ab93b98da',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5501ab93b98db',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5501ab93b98df',
								'label' => 'Button Text',
								'name' => 'button_text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5501ab93b98e1',
								'label' => 'Slant',
								'name' => 'slant',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'block-angle-up' => 'Slant Up',
									'block-angle-down' => 'Slant Down',
									'block-angle-none' => 'No Slant',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_5501ab93b98e2',
								'label' => 'Background Color',
								'name' => 'background_color',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'orange' => 'Orange',
									'blue' => 'Blue',
									'yellow' => 'Yellow',
									'green-lt' => 'Light Green',
									'green' => 'Green',
									'grey-x-lt' => 'Extra Light Grey',
									'grey-lt' => 'Light Grey',
									'grey-dk' => 'Dark Grey',
									'white' => 'White',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_5501abbdb98fb',
								'label' => 'Video Image',
								'name' => 'video_image',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_5501abd5b98fc',
								'label' => 'Vimeo Video ID',
								'name' => 'vimeo_video_id',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
					),
					array (
						'label' => 'Aggregator',
						'name' => 'aggregator',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5487ba36973c4',
								'label' => 'Aggregator Item',
								'name' => 'aggregator_item',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_5487ba40973c5',
										'label' => 'Type',
										'name' => 'type',
										'type' => 'radio',
										'column_width' => '',
										'choices' => array (
											'twitter' => 'Twitter',
											'resource' => 'Resource',
											'blog' => 'Blog',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
									),
									array (
										'key' => 'field_54884965e5b3a',
										'label' => 'Background Color',
										'name' => 'background_color',
										'type' => 'radio',
										'column_width' => '',
										'choices' => array (
											'random' => 'Random',
											'orange' => 'Orange',
											'blue' => 'Blue',
											'yellow' => 'Yellow',
											'green-lt' => 'Light Green',
											'green' => 'Green',
											'grey-lt' => 'Light Grey',
											'grey-dk' => 'Dark Grey',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
									),
									array (
										'key' => 'field_548849b1fcc03',
										'label' => 'Background Image',
										'name' => 'background_image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'url',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Aggregator Item',
							),
						),
					),
					array (
						'label' => 'Resources',
						'name' => 'resources',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5458cdd607e8d',
								'label' => 'Each Resource',
								'name' => 'each_resource',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_5458cdf207e8e',
										'label' => 'Title',
										'name' => 'title',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_5458cdf807e8f',
										'label' => 'Icon',
										'name' => 'icon',
										'type' => 'radio',
										'column_width' => '',
										'choices' => array (
											'ruler' => 'Ruler',
											'arrow' => 'Arrow',
											'finger-press' => 'Finger',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
									),
									array (
										'key' => 'field_5458ce3207e90',
										'label' => 'Color',
										'name' => 'color',
										'type' => 'radio',
										'column_width' => '',
										'choices' => array (
											'orange' => 'Orange',
											'blue' => 'Blue',
											'yellow' => 'Yellow',
											'green-lt' => 'Light Green',
											'green' => 'Green',
											'grey-lt' => 'Light Grey',
											'grey-dk' => 'Dark Grey',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
									),
									array (
										'key' => 'field_5458ce5907e91',
										'label' => 'Category',
										'name' => 'category',
										'type' => 'radio',
										'column_width' => '',
										'choices' => array (
											'content' => 'Content',
											'industry' => 'Industry',
											'use-cases' => 'Use Cases',
											'articles' => 'Articles',
											'white-papers' => 'White Papers',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Resource',
							),
						),
					),
					array (
						'label' => 'Webinars',
						'name' => 'webinars',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
						),
					),
					array (
						'label' => 'Team',
						'name' => 'team',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_545922388e8f4',
								'label' => 'Section Title',
								'name' => 'section_title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5459224a8e8f5',
								'label' => 'Team Member',
								'name' => 'team_member',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_545922da8e8f7',
										'label' => 'Name',
										'name' => 'name',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_545922e78e8f8',
										'label' => 'Title',
										'name' => 'title',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_545922c68e8f6',
										'label' => 'Image',
										'name' => 'image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'url',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_545923228e8f9',
										'label' => 'Bio',
										'name' => 'bio',
										'type' => 'wysiwyg',
										'column_width' => '',
										'default_value' => '',
										'toolbar' => 'full',
										'media_upload' => 'yes',
									),
									array (
										'key' => 'field_5459233f8e8fa',
										'label' => 'Facebook',
										'name' => 'facebook',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_5459235d8e8fb',
										'label' => 'Twitter',
										'name' => 'twitter',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_545923628e8fc',
										'label' => 'Linkedin',
										'name' => 'linkedin',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Team Member',
							),
						),
					),
					array (
						'label' => 'News',
						'name' => 'news',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_545a460704e10',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_545a460b04e11',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
					),
					array (
						'label' => 'Blog',
						'name' => 'blog',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5492e5e5179a6',
								'label' => 'Type',
								'name' => 'type',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'regular' => 'Regular',
									'challenges' => 'Challenges',
									'engineering' => 'Engineering',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'vertical',
							),
						),
					),
					array (
						'label' => 'Partners',
						'name' => 'partners',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
						),
					),
					array (
						'label' => 'Careers',
						'name' => 'careers',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
						),
					),
					array (
						'label' => 'Marketing Stack',
						'name' => 'marketing_stack',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5488701bb697f',
								'label' => 'Stack Item',
								'name' => 'stack_item',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_54887028b6980',
										'label' => 'Size',
										'name' => 'stack_size',
										'type' => 'radio',
										'column_width' => '',
										'choices' => array (
											'stack-sm' => 'Small',
											'stack-lg' => 'Large',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
									),
									array (
										'key' => 'field_5488703ab6981',
										'label' => 'Background Color',
										'name' => 'background_color',
										'type' => 'radio',
										'column_width' => '',
										'choices' => array (
											'random' => 'Random',
											'orange' => 'Orange',
											'blue' => 'Blue',
											'blue-grey' => 'Blue/Grey',
											'yellow' => 'Yellow',
											'green-lt' => 'Light Green',
											'green' => 'Green',
											'grey-lt' => 'Light Grey',
											'grey-dk' => 'Dark Grey',
											'white' => 'White',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
									),
									array (
										'key' => 'field_5488704db6982',
										'label' => 'Title',
										'name' => 'title',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_54887056b6983',
										'label' => 'Content',
										'name' => 'content',
										'type' => 'wysiwyg',
										'column_width' => '',
										'default_value' => '',
										'toolbar' => 'full',
										'media_upload' => 'yes',
									),
									array (
										'key' => 'field_54887060b6984',
										'label' => 'Icon',
										'name' => 'icon',
										'type' => 'file',
										'column_width' => '',
										'save_format' => 'object',
										'library' => 'all',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Stack Item',
							),
						),
					),
					array (
						'label' => 'Collage',
						'name' => 'collage',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5485df14c49ac',
								'label' => 'Collage Item',
								'name' => 'collage_item',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_5485dffec49ad',
										'label' => 'Image',
										'name' => 'image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'url',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_5485e022c49ae',
										'label' => 'Content',
										'name' => 'content',
										'type' => 'wysiwyg',
										'column_width' => '',
										'default_value' => '',
										'toolbar' => 'full',
										'media_upload' => 'yes',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Item',
							),
						),
					),
					array (
						'label' => 'Icon Blocks',
						'name' => 'icon_blocks',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_54870ec12ae91',
								'label' => 'Icon Block',
								'name' => 'icon_block',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_54870ece2ae92',
										'label' => 'Title',
										'name' => 'title',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_54870ee62ae94',
										'label' => 'Content',
										'name' => 'content',
										'type' => 'wysiwyg',
										'column_width' => '',
										'default_value' => '',
										'toolbar' => 'full',
										'media_upload' => 'yes',
									),
									array (
										'key' => 'field_54870eee2ae95',
										'label' => 'Bullets',
										'name' => 'bullets',
										'type' => 'repeater',
										'column_width' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_54870f0e2ae96',
												'label' => 'Bullet Item',
												'name' => 'bullet_item',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
										),
										'row_min' => '',
										'row_limit' => '',
										'layout' => 'row',
										'button_label' => 'Add Bullet',
									),
									array (
										'key' => 'field_54870f252ae97',
										'label' => 'Button',
										'name' => 'button',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_54870f302ae98',
										'label' => 'Button Link',
										'name' => 'button_link',
										'type' => 'page_link',
										'column_width' => '',
										'post_type' => array (
											0 => 'all',
										),
										'allow_null' => 0,
										'multiple' => 0,
									),
									array (
										'key' => 'field_54870ed72ae93',
										'label' => 'Icon',
										'name' => 'icon',
										'type' => 'radio',
										'column_width' => '',
										'choices' => array (
											'graph' => 'Graph',
											'arrow' => 'Arrow',
											'burst' => 'Burst',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
									),
									array (
										'key' => 'field_54871581af8e0',
										'label' => 'Icon Color',
										'name' => 'icon_color',
										'type' => 'radio',
										'column_width' => '',
										'choices' => array (
											'orange' => 'Orange',
											'blue' => 'Blue',
											'yellow' => 'Yellow',
											'green-lt' => 'Light Green',
											'green' => 'Green',
											'grey-x-lt' => 'Extra Light Grey',
											'grey-lt' => 'Light Grey',
											'grey-dk' => 'Dark Grey',
											'white' => 'White',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Block',
							),
						),
					),
					array (
						'label' => 'Contact',
						'name' => 'contact',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
						),
					),
				),
				'button_label' => 'Add Block',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'default',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'resources',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_blogs-settings',
		'title' => 'Blogs\' Settings',
		'fields' => array (
			array (
				'key' => 'field_558b697d653cf',
				'label' => 'Blog',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_558b69a0653d0',
				'label' => 'Blog Header',
				'name' => 'blog_header',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_558b6a22653d1',
						'label' => 'Background',
						'name' => 'background',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_558b6a2c653d2',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_558b6a35653d3',
						'label' => 'Sub-Title',
						'name' => 'sub-title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => 1,
				'layout' => 'row',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_558b85de6bde7',
				'label' => 'Featured Posts in the Sidebar 1',
				'name' => 'blog_featured_posts_sidebar',
				'type' => 'relationship',
				'instructions' => 'Choose up to 6 featured posts to display in the sidebar on the blog.',
				'return_format' => 'object',
				'post_type' => array (
					0 => 'blog',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
				),
				'result_elements' => array (
					0 => 'featured_image',
					1 => 'post_title',
				),
				'max' => 6,
			),
			array (
				'key' => 'field_558b6a44653d4',
				'label' => 'Engineering Blog',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_558b6a51653d5',
				'label' => 'Engineering Blog Header',
				'name' => 'engineering_header',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_558b6a67653d6',
						'label' => 'Background',
						'name' => 'background',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_558b6a71653d7',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_558b6a7a653d8',
						'label' => 'Sub-Title',
						'name' => 'sub-title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => 1,
				'layout' => 'row',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_558b861d6bde8',
				'label' => 'Featured Posts in the Sidebar 2',
				'name' => 'engineering_featured_posts_sidebar',
				'type' => 'relationship',
				'instructions' => 'Choose up to 6 featured posts to display in the sidebar on the blog.',
				'return_format' => 'object',
				'post_type' => array (
					0 => 'engineering',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
				),
				'result_elements' => array (
					0 => 'featured_image',
					1 => 'post_title',
				),
				'max' => 6,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_career-blocks',
		'title' => 'Career Blocks',
		'fields' => array (
			array (
				'key' => 'field_556beb0ecc3b1',
				'label' => 'Career Blocks',
				'name' => 'career_blocks',
				'type' => 'flexible_content',
				'layouts' => array (
					array (
						'label' => 'landing',
						'name' => 'landing',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_556beb2ccc3b2',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_556beb6dcc3b3',
										'label' => 'Heading',
										'name' => 'heading',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
								'row_min' => 1,
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Heading',
							),
							array (
								'key' => 'field_556becad1bc1c',
								'label' => 'Content',
								'name' => 'content',
								'type' => 'textarea',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => '',
								'formatting' => 'br',
							),
							array (
								'key' => 'field_556bed4a3db24',
								'label' => 'Button?',
								'name' => 'button_exists',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_556bfa263db25',
								'label' => 'Button Color',
								'name' => 'button_color',
								'type' => 'radio',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_556bed4a3db24',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'choices' => array (
									'orange' => 'Orange',
									'blue' => 'Blue',
									'yellow' => 'Yellow',
									'green-lt' => 'Light Green',
									'green' => 'Green',
									'grey-lt' => 'Light Grey',
									'grey-dk' => 'Dark Grey',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'grey-dk',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_556bfa733db26',
								'label' => 'Button Text',
								'name' => 'button_text',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_556bed4a3db24',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_556bfa8e3db27',
								'label' => 'Button Link',
								'name' => 'button_link',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_556bed4a3db24',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_556bfac73db28',
								'label' => 'Button Hover Color',
								'name' => 'button_hover_color',
								'type' => 'radio',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_556bed4a3db24',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'choices' => array (
									'orange' => 'Orange',
									'blue' => 'Blue',
									'yellow' => 'Yellow',
									'green-lt' => 'Light Green',
									'green' => 'Green',
									'grey-x-lt' => 'Extra Light Grey',
									'grey-lt' => 'Light Grey',
									'grey-dk' => 'Dark Grey',
									'white' => 'White',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_556bfb3b3db29',
								'label' => 'Banner Image',
								'name' => 'banner_image',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
						),
					),
					array (
						'label' => 'Career Content',
						'name' => 'career_content',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_556d589828022',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_556d58a728023',
								'label' => 'Content',
								'name' => 'content',
								'type' => 'textarea',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => '',
								'formatting' => 'br',
							),
							array (
								'key' => 'field_556d5b0d28029',
								'label' => 'Background Color',
								'name' => 'background_color',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'orange' => 'Orange',
									'blue' => 'Blue',
									'yellow' => 'Yellow',
									'green-lt' => 'Light Green',
									'green' => 'Green',
									'grey-x-lt' => 'Extra Light Grey',
									'grey-lt' => 'Light Grey',
									'grey-dk' => 'Dark Grey',
									'white' => 'White',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'white',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_556d6076dcc09',
								'label' => 'Text Dark?',
								'name' => 'text_dark',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 1,
							),
							array (
								'key' => 'field_556d591928024',
								'label' => 'Button?',
								'name' => 'button_exists',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_556d5a1828025',
								'label' => 'Button Color',
								'name' => 'button_color',
								'type' => 'radio',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_556d591928024',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'choices' => array (
									'orange' => 'Orange',
									'blue' => 'Blue',
									'yellow' => 'Yellow',
									'green-lt' => 'Light Green',
									'green' => 'Green',
									'grey-lt' => 'Light Grey',
									'grey-dk' => 'Dark Grey',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'grey-dk',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_556d5a5828026',
								'label' => 'Button Text',
								'name' => 'button_text',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_556d591928024',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_556d5a7628027',
								'label' => 'Button Link',
								'name' => 'button_link',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_556d591928024',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_556d5ae328028',
								'label' => 'Button Hover Color',
								'name' => 'button_hover_color',
								'type' => 'radio',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_556d591928024',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'choices' => array (
									'orange' => 'Orange',
									'blue' => 'Blue',
									'yellow' => 'Yellow',
									'green-lt' => 'Light Green',
									'green' => 'Green',
									'grey-x-lt' => 'Extra Light Grey',
									'grey-lt' => 'Light Grey',
									'grey-dk' => 'Dark Grey',
									'white' => 'White',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'vertical',
							),
						),
					),
					array (
						'label' => 'Gallery',
						'name' => 'gallery',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_557022b17a15a',
								'label' => 'Background Color',
								'name' => 'background_color',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'orange' => 'Orange',
									'blue' => 'Blue',
									'yellow' => 'Yellow',
									'green-lt' => 'Light Green',
									'green' => 'Green',
									'grey-x-lt' => 'Extra Light Grey',
									'grey-lt' => 'Light Grey',
									'grey-dk' => 'Dark Grey',
									'white' => 'White',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'grey-lt',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_556fee75a16c8',
								'label' => 'Gallery Images',
								'name' => 'gallery_images',
								'type' => 'repeater',
								'instructions' => 'Number of image should be 3 or 4 or 5 or 7. Layout of the gallery will be decided by the application based on the number of image count. ',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_556fee9ea16c9',
										'label' => 'Each Image',
										'name' => 'each_image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'url',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
								),
								'row_min' => '',
								'row_limit' => 7,
								'layout' => 'row',
								'button_label' => 'Add	Image',
							),
						),
					),
					array (
						'label' => 'Icon Block',
						'name' => 'icon_block',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_557109853ee58',
								'label' => 'Slant',
								'name' => 'slant',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'block-angle-up' => 'Slant Up',
									'block-angle-down' => 'Slant Down',
									'block-angle-none' => 'No Slant',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_557109b83ee59',
								'label' => 'Background Color',
								'name' => 'background_color',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'orange' => 'Orange',
									'blue' => 'Blue',
									'yellow' => 'Yellow',
									'green-lt' => 'Light Green',
									'green' => 'Green',
									'grey-x-lt' => 'Extra Light Grey',
									'grey-lt' => 'Light Grey',
									'grey-dk' => 'Dark Grey',
									'white' => 'White',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'white',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_5570a91f29f46',
								'label' => 'Each Icon',
								'name' => 'icon',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_5570a92b29f47',
										'label' => 'Image',
										'name' => 'image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'url',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_5570a95129f48',
										'label' => 'Title',
										'name' => 'title',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_557121d81019d',
										'label' => 'Title Color ',
										'name' => 'title_color_',
										'type' => 'radio',
										'column_width' => '',
										'choices' => array (
											'text-yellow' => 'Yellow',
											'text-blue' => 'Blue',
											'text-orange' => 'Orange',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
									),
									array (
										'key' => 'field_5570a9c729f4b',
										'label' => 'Link?',
										'name' => 'link_exists',
										'type' => 'true_false',
										'column_width' => '',
										'message' => '',
										'default_value' => 0,
									),
									array (
										'key' => 'field_5570a97d29f4a',
										'label' => 'Link',
										'name' => 'link',
										'type' => 'text',
										'conditional_logic' => array (
											'status' => 1,
											'rules' => array (
												array (
													'field' => 'field_5570a9c729f4b',
													'operator' => '==',
													'value' => '1',
												),
											),
											'allorany' => 'all',
										),
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_5570a95729f49',
										'label' => 'Content',
										'name' => 'content',
										'type' => 'textarea',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => '',
										'formatting' => 'br',
									),
									array (
										'key' => 'field_5570aa2250b34',
										'label' => 'Open link in new window?',
										'name' => 'open_link_in_new_window',
										'type' => 'true_false',
										'column_width' => '',
										'message' => '',
										'default_value' => 1,
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Icon Item',
							),
						),
					),
					array (
						'label' => 'Gallery with hover message',
						'name' => 'gallery_with_hover_message',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5570ace96fb5e',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5570aca56fb5d',
								'label' => 'Background Color',
								'name' => 'background_color',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'orange' => 'Orange',
									'blue' => 'Blue',
									'yellow' => 'Yellow',
									'green-lt' => 'Light Green',
									'green' => 'Green',
									'grey-x-lt' => 'Extra Light Grey',
									'grey-lt' => 'Light Grey',
									'grey-dk' => 'Dark Grey',
									'white' => 'White',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'grey-x-lt',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_5570ab986fb59',
								'label' => 'Gallery section',
								'name' => 'gallery_section',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_5570ad53038cb',
										'label' => 'Title',
										'name' => 'title',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_5570abd66fb5a',
										'label' => 'Image',
										'name' => 'image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'url',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_5570ac2d6fb5b',
										'label' => 'Hover Message',
										'name' => 'hover_message',
										'type' => 'textarea',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => '',
										'formatting' => 'br',
									),
									array (
										'key' => 'field_5570ac416fb5c',
										'label' => 'Hover background Color',
										'name' => 'hover_background_color',
										'type' => 'radio',
										'column_width' => '',
										'choices' => array (
											'bg-orange-transparent' => 'Orange',
											'bg-blue-transparent' => 'Blue',
											'bg-yellow-transparent' => 'Yellow',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
									),
									array (
										'key' => 'field_5570ad116fb5f',
										'label' => 'Link',
										'name' => 'link',
										'type' => 'page_link',
										'column_width' => '',
										'post_type' => array (
											0 => 'all',
										),
										'allow_null' => 0,
										'multiple' => 0,
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Row',
							),
						),
					),
					array (
						'label' => 'Open Positions Block ',
						'name' => 'open_positions_block',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_55710a9615573',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => 'OPEN POSITIONS',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_55710abc15574',
								'label' => 'Career Page Type ? ',
								'name' => 'career_page_type',
								'type' => 'radio',
								'instructions' => 'Please select the career page type. Either it is for career home page or for any department page?',
								'column_width' => '',
								'choices' => array (
									'career-home' => 'Career Home Page',
									'career-department' => 'Career Department Page ( Ex: Engineering, Product, Talent etc )',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'career-department',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_55710e90dd1fc',
								'label' => 'Background Color',
								'name' => 'background_color',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'orange' => 'Orange',
									'blue' => 'Blue',
									'yellow' => 'Yellow',
									'green-lt' => 'Light Green',
									'green' => 'Green',
									'grey-x-lt' => 'Extra Light Grey',
									'grey-lt' => 'Light Grey',
									'grey-dk' => 'Dark Grey',
									'white' => 'White',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_5572a15d4fa4e',
								'label' => 'Social Media Section',
								'name' => 'social_media_section',
								'type' => 'repeater',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_55710abc15574',
											'operator' => '==',
											'value' => 'career-home',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_5572a19c4fa4f',
										'label' => 'Title',
										'name' => 'title',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_5572a22e4fa51',
										'label' => 'Social Links',
										'name' => 'social_links',
										'type' => 'repeater',
										'column_width' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_5572a2494fa52',
												'label' => 'Social Site Link',
												'name' => 'social_site_link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_5572a2644fa53',
												'label' => 'Social Icon',
												'name' => 'social_icon',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'url',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
										),
										'row_min' => '',
										'row_limit' => '',
										'layout' => 'row',
										'button_label' => 'Add Social Link',
									),
								),
								'row_min' => 1,
								'row_limit' => 1,
								'layout' => 'row',
								'button_label' => 'Add Social Media Section',
							),
						),
					),
					array (
						'label' => 'Video Block',
						'name' => 'video_block',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5573c8c94e19d',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5573c8d44e19e',
								'label' => 'Sub Title',
								'name' => 'sub_title',
								'type' => 'textarea',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => '',
								'formatting' => 'br',
							),
							array (
								'key' => 'field_5573c9044e19f',
								'label' => 'Video URL',
								'name' => 'video_url',
								'type' => 'text',
								'instructions' => 'EX: https://www.youtube.com/embed/tTeCesrq9P4',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5573cb98de958',
								'label' => 'Button?',
								'name' => 'button_exists',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_5573cbbdde959',
								'label' => 'First Button Text',
								'name' => 'first_button_text',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_5573cb98de958',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5573cbe3de95a',
								'label' => 'First Button Link',
								'name' => 'first_button_link',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_5573cb98de958',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5573cc35de95d',
								'label' => 'First Button Color',
								'name' => 'first_button_color',
								'type' => 'radio',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_5573cb98de958',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'choices' => array (
									'orange' => 'Orange',
									'blue' => 'Blue',
									'yellow' => 'Yellow',
									'green-lt' => 'Light Green',
									'green' => 'Green',
									'grey-lt' => 'Light Grey',
									'grey-dk' => 'Dark Grey',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'orange',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_5573cc64de95e',
								'label' => 'First Button Hover Color',
								'name' => 'first_button_hover_color',
								'type' => 'radio',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_5573cb98de958',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'choices' => array (
									'orange' => 'Orange',
									'blue' => 'Blue',
									'yellow' => 'Yellow',
									'green-lt' => 'Light Green',
									'green' => 'Green',
									'grey-x-lt' => 'Extra Light Grey',
									'grey-lt' => 'Light Grey',
									'grey-dk' => 'Dark Grey',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'blue',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_5573cbf4de95b',
								'label' => 'Second Button Text',
								'name' => 'second_button_text',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_5573cb98de958',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5573cc0bde95c',
								'label' => 'Second Button Link',
								'name' => 'second_button_link',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_5573cb98de958',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5573cd03de95f',
								'label' => 'Second Button Color',
								'name' => 'second_button_color',
								'type' => 'radio',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_5573cb98de958',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'choices' => array (
									'orange' => 'Orange',
									'blue' => 'Blue',
									'yellow' => 'Yellow',
									'green-lt' => 'Light Green',
									'green' => 'Green',
									'grey-lt' => 'Light Grey',
									'grey-dk' => 'Dark Grey',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'yellow',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_5573cda7de960',
								'label' => 'Second Button Hover Color',
								'name' => 'second_button_hover_color',
								'type' => 'radio',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_5573cb98de958',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'choices' => array (
									'orange' => 'Orange',
									'blue' => 'Blue',
									'yellow' => 'Yellow',
									'green-lt' => 'Light Green',
									'green' => 'Green',
									'grey-x-lt' => 'Extra Light Grey',
									'grey-lt' => 'Light Grey',
									'grey-dk' => 'Dark Grey',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'blue',
								'layout' => 'vertical',
							),
						),
					),
					array (
						'label' => 'Banner Image',
						'name' => 'banner_image',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5573e5b57a6b4',
								'label' => 'Top Banner Image',
								'name' => 'top_banner_image',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
						),
					),
					array (
						'label' => 'Interns Block',
						'name' => 'interns_block',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_55742c98d507a',
								'label' => 'Each Intern',
								'name' => 'each_intern',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_55742cd7d507b',
										'label' => 'Name',
										'name' => 'name',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_55742d82f33e6',
										'label' => 'Image',
										'name' => 'image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'url',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_55742ce0d507c',
										'label' => 'Message',
										'name' => 'message',
										'type' => 'textarea',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => '',
										'formatting' => 'br',
									),
									array (
										'key' => 'field_55742d09d507d',
										'label' => 'Link',
										'name' => 'link',
										'type' => 'page_link',
										'column_width' => '',
										'post_type' => array (
											0 => 'all',
										),
										'allow_null' => 0,
										'multiple' => 0,
									),
									array (
										'key' => 'field_557430f503430',
										'label' => 'Link Text',
										'name' => 'link_text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => 'Read More',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Intern',
							),
						),
					),
					array (
						'label' => 'Job Index',
						'name' => 'job_index',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
						),
					),
				),
				'button_label' => 'Add Career Block',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 0,
				),
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'tmp/template-career.php',
					'order_no' => 1,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_careers',
		'title' => 'Careers',
		'fields' => array (
			array (
				'key' => 'field_546caa67b703e',
				'label' => 'Application ID',
				'name' => 'application_id',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_546cbb67eb7ce',
				'label' => 'Careers Info',
				'name' => 'careers_info',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'careers',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_news',
		'title' => 'News',
		'fields' => array (
			array (
				'key' => 'field_545a3f8727294',
				'label' => 'External Link',
				'name' => 'external_link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_546e394561713',
				'label' => 'Featured?',
				'name' => 'is_featured',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5497112d7b467',
				'label' => 'Press',
				'name' => 'is_press',
				'type' => 'true_false',
				'instructions' => 'Is this a press release?',
				'message' => '',
				'default_value' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'news',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_partners',
		'title' => 'Partners',
		'fields' => array (
			array (
				'key' => 'field_546e0e6c99e91',
				'label' => 'Partner Website',
				'name' => 'partner_website',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'partners',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_resource-link-data',
		'title' => 'Resource Link Data',
		'fields' => array (
			array (
				'key' => 'field_55e4dbbaee2e1',
				'label' => 'Link Type',
				'name' => 'link_type',
				'type' => 'radio',
				'choices' => array (
					'resource' => 'Resource',
					'video' => 'Video',
					'news' => 'News',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_55e4df5574184',
				'label' => 'Resource Sub-Type',
				'name' => 'doc_sub_type',
				'type' => 'radio',
				'instructions' => 'Group items together using this sub-type.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55e4dbbaee2e1',
							'operator' => '==',
							'value' => 'resource',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'datasheet' => 'Datasheet',
					'case_study' => 'Case Study',
					'whitepaper' => 'Whitepaper',
					'solution' => 'Solution Brief',
				),
				'other_choice' => 1,
				'save_other_choice' => 1,
				'default_value' => '',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_55e4dfabc9627',
				'label' => 'Webinar / Video Sub-Type',
				'name' => 'webinar_video_sub_type',
				'type' => 'radio',
				'instructions' => 'Group items together using this sub-type.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55e4dbbaee2e1',
							'operator' => '==',
							'value' => 'video',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'Webinar' => 'Webinar',
				),
				'other_choice' => 1,
				'save_other_choice' => 1,
				'default_value' => '',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_55e4dfc9c9628',
				'label' => 'Blog Post Sub-Type',
				'name' => 'blog_post_sub_type',
				'type' => 'radio',
				'instructions' => 'Group items together using this sub-type.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55e4dbbaee2e1',
							'operator' => '==',
							'value' => 'news',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
				),
				'other_choice' => 1,
				'save_other_choice' => 1,
				'default_value' => '',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_55c92671d52af',
				'label' => 'Link Label',
				'name' => 'link_label',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55e4dbbaee2e1',
							'operator' => '!=',
							'value' => 'news',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55e4dbffee2e2',
				'label' => 'Blog Post',
				'name' => 'blog_post',
				'type' => 'relationship',
				'instructions' => 'Choose a blog post from the list on the left. Limit 1.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55e4dbbaee2e1',
							'operator' => '==',
							'value' => 'news',
						),
					),
					'allorany' => 'all',
				),
				'return_format' => 'object',
				'post_type' => array (
					0 => 'news',
					1 => 'blog',
					2 => 'engineering',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
					1 => 'post_type',
				),
				'result_elements' => array (
					0 => 'featured_image',
					1 => 'post_type',
					2 => 'post_title',
				),
				'max' => 1,
			),
			array (
				'key' => 'field_55e4dc96d7bcc',
				'label' => 'Thumbnail',
				'name' => 'thumbnail',
				'type' => 'image',
				'instructions' => 'Upload or select an image to use as a thumbnail for this link.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55e4dbbaee2e1',
							'operator' => '==',
							'value' => 'video',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'object',
				'preview_size' => 'blog-thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_55c9257950a6c',
				'label' => 'Link URL',
				'name' => 'link_url',
				'type' => 'text',
				'instructions' => 'Include http://',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55e4dbbaee2e1',
							'operator' => '==',
							'value' => 'resource',
						),
						array (
							'field' => 'field_55e4dbbaee2e1',
							'operator' => '==',
							'value' => 'video',
						),
					),
					'allorany' => 'any',
				),
				'default_value' => 'http://',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'resource_link',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_resources',
		'title' => 'Resources',
		'fields' => array (
			array (
				'key' => 'field_545ce0a691b12',
				'label' => 'Icon',
				'name' => 'icon',
				'type' => 'radio',
				'choices' => array (
					'graph' => 'Graph',
					'graph-thick' => 'Thick Graph',
					'arrow' => 'Arrow',
					'arrow-thick' => 'Thick Arrow',
					'burst' => 'Burst',
					'burst-thick' => 'Thick Burst',
					'ruler' => 'Ruler',
					'finger-press' => 'Finger',
					'travel' => 'Travel',
					'telco' => 'Telco',
					'financial' => 'Financial',
					'auto' => 'Auto',
					'e-commerce' => 'E-commerce',
					'publisher' => 'Publisher',
					'audience-extension' => 'Audience Extension',
					'lightning' => 'Lightning',
					'smile' => 'Smile',
					'dialogue' => 'Dialogue',
					'magazine' => 'Magazine',
					'whitepaper' => 'Whitepaper',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_545ce0d391b13',
				'label' => 'Color',
				'name' => 'color',
				'type' => 'radio',
				'choices' => array (
					'orange' => 'Orange',
					'blue' => 'Blue',
					'yellow' => 'Yellow',
					'green-lt' => 'Light Green',
					'green' => 'Green',
					'grey-lt' => 'Light Grey',
					'grey-dk' => 'Dark Grey',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_5473400c782c7',
				'label' => 'Featured Resource?',
				'name' => 'featured_resource',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_54733f38bd54b',
				'label' => 'Resources Excerpt',
				'name' => 'resources_excerpt',
				'type' => 'wysiwyg',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5473400c782c7',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_548b3dd43dc2c',
				'label' => 'Download',
				'name' => 'download',
				'type' => 'file',
				'save_format' => 'url',
				'library' => 'all',
			),
			array (
				'key' => 'field_5491d020a6cfe',
				'label' => 'Marketo?',
				'name' => 'marketo',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'resources',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_webinars',
		'title' => 'Webinars',
		'fields' => array (
			array (
				'key' => 'field_546a34da88142',
				'label' => 'Webinar Link',
				'name' => 'webinar_link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'webinars',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_resource-link-pages',
		'title' => 'Resource Link Pages',
		'fields' => array (
			array (
				'key' => 'field_55e4dd20e124d',
				'label' => 'link_pages',
				'name' => 'link_pages',
				'type' => 'relationship',
				'instructions' => 'Select all pages where this resource link should display.',
				'return_format' => 'object',
				'post_type' => array (
					0 => 'page',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
					1 => 'post_type',
				),
				'result_elements' => array (
					0 => 'post_type',
					1 => 'post_title',
				),
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'resource_link',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 10,
	));
}
