<?php

if(function_exists("register_field_group")):

register_field_group(array (
	'id' => 'acf_career-blocks',
	'title' => 'Career Blocks',
	'fields' => array (
		array (
			'key' => 'field_556beb0ecc3b1',
			'label' => 'Career Blocks',
			'name' => 'career_blocks',
			'type' => 'flexible_content',
			'layouts' => array (
				array (
					'label' => 'landing',
					'name' => 'landing',
					'display' => 'row',
					'min' => '',
					'max' => '',
					'sub_fields' => array (
						array (
							'key' => 'field_556beb2ccc3b2',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'repeater',
							'column_width' => '',
							'sub_fields' => array (
								array (
									'key' => 'field_556beb6dcc3b3',
									'label' => 'Heading',
									'name' => 'heading',
									'type' => 'text',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'html',
									'maxlength' => '',
								),
							),
							'row_min' => 1,
							'row_limit' => '',
							'layout' => 'row',
							'button_label' => 'Add Heading',
						),
						array (
							'key' => 'field_556becad1bc1c',
							'label' => 'Content',
							'name' => 'content',
							'type' => 'textarea',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'formatting' => 'br',
						),
						array (
							'key' => 'field_556bed4a3db24',
							'label' => 'Button?',
							'name' => 'button_exists',
							'type' => 'true_false',
							'column_width' => '',
							'message' => '',
							'default_value' => 0,
						),
						array (
							'key' => 'field_556bfa263db25',
							'label' => 'Button Color',
							'name' => 'button_color',
							'type' => 'radio',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_556bed4a3db24',
										'operator' => '==',
										'value' => '1',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => '',
							'choices' => array (
								'orange' => 'Orange',
								'blue' => 'Blue',
								'yellow' => 'Yellow',
								'green-lt' => 'Light Green',
								'green' => 'Green',
								'grey-lt' => 'Light Grey',
								'grey-dk' => 'Dark Grey',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'grey-dk',
							'layout' => 'vertical',
						),
						array (
							'key' => 'field_556bfa733db26',
							'label' => 'Button Text',
							'name' => 'button_text',
							'type' => 'text',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_556bed4a3db24',
										'operator' => '==',
										'value' => '1',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_556bfa8e3db27',
							'label' => 'Button Link',
							'name' => 'button_link',
							'type' => 'text',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_556bed4a3db24',
										'operator' => '==',
										'value' => '1',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_556bfac73db28',
							'label' => 'Button Hover Color',
							'name' => 'button_hover_color',
							'type' => 'radio',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_556bed4a3db24',
										'operator' => '==',
										'value' => '1',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => '',
							'choices' => array (
								'orange' => 'Orange',
								'blue' => 'Blue',
								'yellow' => 'Yellow',
								'green-lt' => 'Light Green',
								'green' => 'Green',
								'grey-x-lt' => 'Extra Light Grey',
								'grey-lt' => 'Light Grey',
								'grey-dk' => 'Dark Grey',
								'white' => 'White',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
						),
						array (
							'key' => 'field_556bfb3b3db29',
							'label' => 'Banner Image',
							'name' => 'banner_image',
							'type' => 'image',
							'column_width' => '',
							'save_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
						),
					),
				),
				array (
					'label' => 'Career Content',
					'name' => 'career_content',
					'display' => 'row',
					'min' => '',
					'max' => '',
					'sub_fields' => array (
						array (
							'key' => 'field_556d589828022',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_556d58a728023',
							'label' => 'Content',
							'name' => 'content',
							'type' => 'textarea',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'formatting' => 'br',
						),
						array (
							'key' => 'field_556d5b0d28029',
							'label' => 'Background Color',
							'name' => 'background_color',
							'type' => 'radio',
							'column_width' => '',
							'choices' => array (
								'orange' => 'Orange',
								'blue' => 'Blue',
								'yellow' => 'Yellow',
								'green-lt' => 'Light Green',
								'green' => 'Green',
								'grey-x-lt' => 'Extra Light Grey',
								'grey-lt' => 'Light Grey',
								'grey-dk' => 'Dark Grey',
								'white' => 'White',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'white',
							'layout' => 'vertical',
						),
						array (
							'key' => 'field_556d6076dcc09',
							'label' => 'Text Dark?',
							'name' => 'text_dark',
							'type' => 'true_false',
							'column_width' => '',
							'message' => '',
							'default_value' => 1,
						),
						array (
							'key' => 'field_556d591928024',
							'label' => 'Button?',
							'name' => 'button_exists',
							'type' => 'true_false',
							'column_width' => '',
							'message' => '',
							'default_value' => 0,
						),
						array (
							'key' => 'field_556d5a1828025',
							'label' => 'Button Color',
							'name' => 'button_color',
							'type' => 'radio',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_556d591928024',
										'operator' => '==',
										'value' => '1',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => '',
							'choices' => array (
								'orange' => 'Orange',
								'blue' => 'Blue',
								'yellow' => 'Yellow',
								'green-lt' => 'Light Green',
								'green' => 'Green',
								'grey-lt' => 'Light Grey',
								'grey-dk' => 'Dark Grey',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'grey-dk',
							'layout' => 'vertical',
						),
						array (
							'key' => 'field_556d5a5828026',
							'label' => 'Button Text',
							'name' => 'button_text',
							'type' => 'text',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_556d591928024',
										'operator' => '==',
										'value' => '1',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_556d5a7628027',
							'label' => 'Button Link',
							'name' => 'button_link',
							'type' => 'text',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_556d591928024',
										'operator' => '==',
										'value' => '1',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_556d5ae328028',
							'label' => 'Button Hover Color',
							'name' => 'button_hover_color',
							'type' => 'radio',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_556d591928024',
										'operator' => '==',
										'value' => '1',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => '',
							'choices' => array (
								'orange' => 'Orange',
								'blue' => 'Blue',
								'yellow' => 'Yellow',
								'green-lt' => 'Light Green',
								'green' => 'Green',
								'grey-x-lt' => 'Extra Light Grey',
								'grey-lt' => 'Light Grey',
								'grey-dk' => 'Dark Grey',
								'white' => 'White',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
						),
					),
				),
				array (
					'label' => 'Gallery',
					'name' => 'gallery',
					'display' => 'row',
					'min' => '',
					'max' => '',
					'sub_fields' => array (
						array (
							'key' => 'field_557022b17a15a',
							'label' => 'Background Color',
							'name' => 'background_color',
							'type' => 'radio',
							'column_width' => '',
							'choices' => array (
								'orange' => 'Orange',
								'blue' => 'Blue',
								'yellow' => 'Yellow',
								'green-lt' => 'Light Green',
								'green' => 'Green',
								'grey-x-lt' => 'Extra Light Grey',
								'grey-lt' => 'Light Grey',
								'grey-dk' => 'Dark Grey',
								'white' => 'White',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'grey-lt',
							'layout' => 'vertical',
						),
						array (
							'key' => 'field_556fee75a16c8',
							'label' => 'Gallery Images',
							'name' => 'gallery_images',
							'type' => 'repeater',
							'instructions' => 'Number of image should be 3 or 4 or 5 or 7. Layout of the gallery will be decided by the application based on the number of image count. ',
							'column_width' => '',
							'sub_fields' => array (
								array (
									'key' => 'field_556fee9ea16c9',
									'label' => 'Each Image',
									'name' => 'each_image',
									'type' => 'image',
									'column_width' => '',
									'save_format' => 'url',
									'preview_size' => 'thumbnail',
									'library' => 'all',
								),
							),
							'row_min' => '',
							'row_limit' => 7,
							'layout' => 'row',
							'button_label' => 'Add	Image',
						),
					),
				),
				array (
					'label' => 'Icon Block',
					'name' => 'icon_block',
					'display' => 'row',
					'min' => '',
					'max' => '',
					'sub_fields' => array (
						array (
							'key' => 'field_557109853ee58',
							'label' => 'Slant',
							'name' => 'slant',
							'type' => 'radio',
							'column_width' => '',
							'choices' => array (
								'block-angle-up' => 'Slant Up',
								'block-angle-down' => 'Slant Down',
								'block-angle-none' => 'No Slant',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
						),
						array (
							'key' => 'field_557109b83ee59',
							'label' => 'Background Color',
							'name' => 'background_color',
							'type' => 'radio',
							'column_width' => '',
							'choices' => array (
								'orange' => 'Orange',
								'blue' => 'Blue',
								'yellow' => 'Yellow',
								'green-lt' => 'Light Green',
								'green' => 'Green',
								'grey-x-lt' => 'Extra Light Grey',
								'grey-lt' => 'Light Grey',
								'grey-dk' => 'Dark Grey',
								'white' => 'White',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'white',
							'layout' => 'vertical',
						),
						array (
							'key' => 'field_5570a91f29f46',
							'label' => 'Each Icon',
							'name' => 'icon',
							'type' => 'repeater',
							'column_width' => '',
							'sub_fields' => array (
								array (
									'key' => 'field_5570a92b29f47',
									'label' => 'Image',
									'name' => 'image',
									'type' => 'image',
									'column_width' => '',
									'save_format' => 'url',
									'preview_size' => 'thumbnail',
									'library' => 'all',
								),
								array (
									'key' => 'field_5570a95129f48',
									'label' => 'Title',
									'name' => 'title',
									'type' => 'text',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'html',
									'maxlength' => '',
								),
								array (
									'key' => 'field_557121d81019d',
									'label' => 'Title Color ',
									'name' => 'title_color_',
									'type' => 'radio',
									'column_width' => '',
									'choices' => array (
										'text-yellow' => 'Yellow',
										'text-blue' => 'Blue',
										'text-orange' => 'Orange',
									),
									'other_choice' => 0,
									'save_other_choice' => 0,
									'default_value' => '',
									'layout' => 'vertical',
								),
								array (
									'key' => 'field_5570a9c729f4b',
									'label' => 'Link?',
									'name' => 'link_exists',
									'type' => 'true_false',
									'column_width' => '',
									'message' => '',
									'default_value' => 0,
								),
								array (
									'key' => 'field_5570a97d29f4a',
									'label' => 'Link',
									'name' => 'link',
									'type' => 'text',
									'conditional_logic' => array (
										'status' => 1,
										'rules' => array (
											array (
												'field' => 'field_5570a9c729f4b',
												'operator' => '==',
												'value' => '1',
											),
										),
										'allorany' => 'all',
									),
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'html',
									'maxlength' => '',
								),
								array (
									'key' => 'field_5570a95729f49',
									'label' => 'Content',
									'name' => 'content',
									'type' => 'textarea',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => '',
									'formatting' => 'br',
								),
								array (
									'key' => 'field_5570aa2250b34',
									'label' => 'Open link in new window?',
									'name' => 'open_link_in_new_window',
									'type' => 'true_false',
									'column_width' => '',
									'message' => '',
									'default_value' => 1,
								),
							),
							'row_min' => '',
							'row_limit' => '',
							'layout' => 'row',
							'button_label' => 'Add Icon Item',
						),
					),
				),
				array (
					'label' => 'Gallery with hover message',
					'name' => 'gallery_with_hover_message',
					'display' => 'row',
					'min' => '',
					'max' => '',
					'sub_fields' => array (
						array (
							'key' => 'field_5570ace96fb5e',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_5570aca56fb5d',
							'label' => 'Background Color',
							'name' => 'background_color',
							'type' => 'radio',
							'column_width' => '',
							'choices' => array (
								'orange' => 'Orange',
								'blue' => 'Blue',
								'yellow' => 'Yellow',
								'green-lt' => 'Light Green',
								'green' => 'Green',
								'grey-x-lt' => 'Extra Light Grey',
								'grey-lt' => 'Light Grey',
								'grey-dk' => 'Dark Grey',
								'white' => 'White',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'grey-x-lt',
							'layout' => 'vertical',
						),
						array (
							'key' => 'field_5570ab986fb59',
							'label' => 'Gallery section',
							'name' => 'gallery_section',
							'type' => 'repeater',
							'column_width' => '',
							'sub_fields' => array (
								array (
									'key' => 'field_5570ad53038cb',
									'label' => 'Title',
									'name' => 'title',
									'type' => 'text',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'html',
									'maxlength' => '',
								),
								array (
									'key' => 'field_5570abd66fb5a',
									'label' => 'Image',
									'name' => 'image',
									'type' => 'image',
									'column_width' => '',
									'save_format' => 'url',
									'preview_size' => 'thumbnail',
									'library' => 'all',
								),
								array (
									'key' => 'field_5570ac2d6fb5b',
									'label' => 'Hover Message',
									'name' => 'hover_message',
									'type' => 'textarea',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => '',
									'formatting' => 'br',
								),
								array (
									'key' => 'field_5570ac416fb5c',
									'label' => 'Hover background Color',
									'name' => 'hover_background_color',
									'type' => 'radio',
									'column_width' => '',
									'choices' => array (
										'bg-orange-transparent' => 'Orange',
										'bg-blue-transparent' => 'Blue',
										'bg-yellow-transparent' => 'Yellow',
									),
									'other_choice' => 0,
									'save_other_choice' => 0,
									'default_value' => '',
									'layout' => 'vertical',
								),
								array (
									'key' => 'field_5570ad116fb5f',
									'label' => 'Link',
									'name' => 'link',
									'type' => 'page_link',
									'column_width' => '',
									'post_type' => array (
										0 => 'all',
									),
									'allow_null' => 0,
									'multiple' => 0,
								),
							),
							'row_min' => '',
							'row_limit' => '',
							'layout' => 'row',
							'button_label' => 'Add Row',
						),
					),
				),
				array (
					'label' => 'Open Positions Block ',
					'name' => 'open_positions_block',
					'display' => 'row',
					'min' => '',
					'max' => '',
					'sub_fields' => array (
						array (
							'key' => 'field_55710a9615573',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'column_width' => '',
							'default_value' => 'OPEN POSITIONS',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_55710abc15574',
							'label' => 'Career Page Type ? ',
							'name' => 'career_page_type',
							'type' => 'radio',
							'instructions' => 'Please select the career page type. Either it is for career home page or for any department page?',
							'column_width' => '',
							'choices' => array (
								'career-home' => 'Career Home Page',
								'career-department' => 'Career Department Page ( Ex: Engineering, Product, Talent etc )',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'career-department',
							'layout' => 'vertical',
						),
						array (
							'key' => 'field_55710e90dd1fc',
							'label' => 'Background Color',
							'name' => 'background_color',
							'type' => 'radio',
							'column_width' => '',
							'choices' => array (
								'orange' => 'Orange',
								'blue' => 'Blue',
								'yellow' => 'Yellow',
								'green-lt' => 'Light Green',
								'green' => 'Green',
								'grey-x-lt' => 'Extra Light Grey',
								'grey-lt' => 'Light Grey',
								'grey-dk' => 'Dark Grey',
								'white' => 'White',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
						),
						array (
							'key' => 'field_5572a15d4fa4e',
							'label' => 'Social Media Section',
							'name' => 'social_media_section',
							'type' => 'repeater',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_55710abc15574',
										'operator' => '==',
										'value' => 'career-home',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => '',
							'sub_fields' => array (
								array (
									'key' => 'field_5572a19c4fa4f',
									'label' => 'Title',
									'name' => 'title',
									'type' => 'text',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'html',
									'maxlength' => '',
								),
								array (
									'key' => 'field_5572a22e4fa51',
									'label' => 'Social Links',
									'name' => 'social_links',
									'type' => 'repeater',
									'column_width' => '',
									'sub_fields' => array (
										array (
											'key' => 'field_5572a2494fa52',
											'label' => 'Social Site Link',
											'name' => 'social_site_link',
											'type' => 'text',
											'column_width' => '',
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'formatting' => 'html',
											'maxlength' => '',
										),
										array (
											'key' => 'field_5572a2644fa53',
											'label' => 'Social Icon',
											'name' => 'social_icon',
											'type' => 'image',
											'column_width' => '',
											'save_format' => 'url',
											'preview_size' => 'thumbnail',
											'library' => 'all',
										),
									),
									'row_min' => '',
									'row_limit' => '',
									'layout' => 'row',
									'button_label' => 'Add Social Link',
								),
							),
							'row_min' => 1,
							'row_limit' => 1,
							'layout' => 'row',
							'button_label' => 'Add Social Media Section',
						),
					),
				),
				array (
					'label' => 'Video Block',
					'name' => 'video_block',
					'display' => 'row',
					'min' => '',
					'max' => '',
					'sub_fields' => array (
						array (
							'key' => 'field_5573c8c94e19d',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_5573c8d44e19e',
							'label' => 'Sub Title',
							'name' => 'sub_title',
							'type' => 'textarea',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'formatting' => 'br',
						),
						array (
							'key' => 'field_5573c9044e19f',
							'label' => 'Video URL',
							'name' => 'video_url',
							'type' => 'text',
							'instructions' => 'EX: https://www.youtube.com/embed/tTeCesrq9P4',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_5573cb98de958',
							'label' => 'Button?',
							'name' => 'button_exists',
							'type' => 'true_false',
							'column_width' => '',
							'message' => '',
							'default_value' => 0,
						),
						array (
							'key' => 'field_5573cbbdde959',
							'label' => 'First Button Text',
							'name' => 'first_button_text',
							'type' => 'text',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_5573cb98de958',
										'operator' => '==',
										'value' => '1',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_5573cbe3de95a',
							'label' => 'First Button Link',
							'name' => 'first_button_link',
							'type' => 'text',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_5573cb98de958',
										'operator' => '==',
										'value' => '1',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_5573cc35de95d',
							'label' => 'First Button Color',
							'name' => 'first_button_color',
							'type' => 'radio',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_5573cb98de958',
										'operator' => '==',
										'value' => '1',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => '',
							'choices' => array (
								'orange' => 'Orange',
								'blue' => 'Blue',
								'yellow' => 'Yellow',
								'green-lt' => 'Light Green',
								'green' => 'Green',
								'grey-lt' => 'Light Grey',
								'grey-dk' => 'Dark Grey',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'orange',
							'layout' => 'vertical',
						),
						array (
							'key' => 'field_5573cc64de95e',
							'label' => 'First Button Hover Color',
							'name' => 'first_button_hover_color',
							'type' => 'radio',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_5573cb98de958',
										'operator' => '==',
										'value' => '1',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => '',
							'choices' => array (
								'orange' => 'Orange',
								'blue' => 'Blue',
								'yellow' => 'Yellow',
								'green-lt' => 'Light Green',
								'green' => 'Green',
								'grey-x-lt' => 'Extra Light Grey',
								'grey-lt' => 'Light Grey',
								'grey-dk' => 'Dark Grey',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'blue',
							'layout' => 'vertical',
						),
						array (
							'key' => 'field_5573cbf4de95b',
							'label' => 'Second Button Text',
							'name' => 'second_button_text',
							'type' => 'text',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_5573cb98de958',
										'operator' => '==',
										'value' => '1',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_5573cc0bde95c',
							'label' => 'Second Button Link',
							'name' => 'second_button_link',
							'type' => 'text',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_5573cb98de958',
										'operator' => '==',
										'value' => '1',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_5573cd03de95f',
							'label' => 'Second Button Color',
							'name' => 'second_button_color',
							'type' => 'radio',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_5573cb98de958',
										'operator' => '==',
										'value' => '1',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => '',
							'choices' => array (
								'orange' => 'Orange',
								'blue' => 'Blue',
								'yellow' => 'Yellow',
								'green-lt' => 'Light Green',
								'green' => 'Green',
								'grey-lt' => 'Light Grey',
								'grey-dk' => 'Dark Grey',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'yellow',
							'layout' => 'vertical',
						),
						array (
							'key' => 'field_5573cda7de960',
							'label' => 'Second Button Hover Color',
							'name' => 'second_button_hover_color',
							'type' => 'radio',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_5573cb98de958',
										'operator' => '==',
										'value' => '1',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => '',
							'choices' => array (
								'orange' => 'Orange',
								'blue' => 'Blue',
								'yellow' => 'Yellow',
								'green-lt' => 'Light Green',
								'green' => 'Green',
								'grey-x-lt' => 'Extra Light Grey',
								'grey-lt' => 'Light Grey',
								'grey-dk' => 'Dark Grey',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'blue',
							'layout' => 'vertical',
						),
					),
				),
				array (
					'label' => 'Banner Image',
					'name' => 'banner_image',
					'display' => 'row',
					'min' => '',
					'max' => '',
					'sub_fields' => array (
						array (
							'key' => 'field_5573e5b57a6b4',
							'label' => 'Top Banner Image',
							'name' => 'top_banner_image',
							'type' => 'image',
							'column_width' => '',
							'save_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
						),
					),
				),
				array (
					'label' => 'Interns Block',
					'name' => 'interns_block',
					'display' => 'row',
					'min' => '',
					'max' => '',
					'sub_fields' => array (
						array (
							'key' => 'field_55742c98d507a',
							'label' => 'Each Intern',
							'name' => 'each_intern',
							'type' => 'repeater',
							'column_width' => '',
							'sub_fields' => array (
								array (
									'key' => 'field_55742cd7d507b',
									'label' => 'Name',
									'name' => 'name',
									'type' => 'text',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'html',
									'maxlength' => '',
								),
								array (
									'key' => 'field_55742d82f33e6',
									'label' => 'Image',
									'name' => 'image',
									'type' => 'image',
									'column_width' => '',
									'save_format' => 'url',
									'preview_size' => 'thumbnail',
									'library' => 'all',
								),
								array (
									'key' => 'field_55742ce0d507c',
									'label' => 'Message',
									'name' => 'message',
									'type' => 'textarea',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => '',
									'formatting' => 'br',
								),
								array (
									'key' => 'field_55742d09d507d',
									'label' => 'Link',
									'name' => 'link',
									'type' => 'page_link',
									'column_width' => '',
									'post_type' => array (
										0 => 'all',
									),
									'allow_null' => 0,
									'multiple' => 0,
								),
								array (
									'key' => 'field_557430f503430',
									'label' => 'Link Text',
									'name' => 'link_text',
									'type' => 'text',
									'column_width' => '',
									'default_value' => 'Read More',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'html',
									'maxlength' => '',
								),
							),
							'row_min' => '',
							'row_limit' => '',
							'layout' => 'row',
							'button_label' => 'Add Intern',
						),
					),
				),
				array (
					'label' => 'Job Index',
					'name' => 'job_index',
					'display' => 'row',
					'min' => '',
					'max' => '',
					'sub_fields' => array (
					),
				),
			),
			'button_label' => 'Add Career Block',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
				'order_no' => 0,
				'group_no' => 0,
			),
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'tmp/template-career.php',
				'order_no' => 1,
				'group_no' => 0,
			),
		),
	),
	'options' => array (
		'position' => 'normal',
		'layout' => 'no_box',
		'hide_on_screen' => array (
		),
	),
	'menu_order' => 0,
));

endif;
