<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_57ca192b2c657',
        'title' => 'Hero',
        'fields' => array(
            array(
                'key' => 'field_586fd7344e1b6',
                'label' => 'Hero Title Override',
                'name' => 'hero_title_override',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array(
                'key' => 'field_57e9d910ee458',
                'label' => 'Hero Icon',
                'name' => 'hero_icon',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'Agencies' => 'Agencies',
                    'Applying Identity' => 'Applying Identity',
                    'Brands' => 'Brands',
                    'Connect' => 'Connect',
                    'Data Monetization' => 'Data Monetization',
                    'Data Owners' => 'Data Owners',
                    'Data Store' => 'Data Store',
                    'Discover Identity' => 'Discover Identity',
                    'Features Connect' => 'Features Connect',
                    'Identity Graph' => 'Identity Graph',
                    'Identity Link Features' => 'Identity Link Features',
                    'Identity Resolution' => 'Identity Resolution',
                    'Identity' => 'Identity',
                    'Measurement' => 'Measurement',
                    'Omnichannel' => 'Omnichannel',
                    'Onboarding' => 'Onboarding',
                    'Overview' => 'Overview',
                    'People Based Marketing' => 'People Based Marketing',
                    'Personalization' => 'Personalization',
                    'Platform' => 'Platform',
                    'Publishers' => 'Publishers',
                    'Safehaven' => 'Safehaven',
                    'Targeting' => 'Targeting',
                    'TV' => 'TV',
                    'Slider Brands' => 'Slider Brands',
                    'Slider Identity' => 'Slider Identity',
                    'Slider Platform' => 'Slider Platform',
                    'Slider Publishers' => 'Slider Publishers',
                    'Slider Data Owners' => 'Slider Data Owners',
                    'Slider Targeting' => 'Slider Targeting',
                    'Slider People Based Search' => 'Slider People Based Search',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'disabled' => 0,
                'readonly' => 0,
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_5afcc23c20fec',
                'label' => 'Select Background Type',
                'name' => 'select_background_type',
                'type' => 'select',
                'instructions' => 'Background type can be static, or a video. This is separate from the on-click video.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'image' => 'Image',
                    'video' => 'Video',
                ),
                'default_value' => array(
                    0 => 'Image',
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_57ca192fd2612',
                'label' => 'Hero Image',
                'name' => 'hero_image',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5afcc23c20fec',
                            'operator' => '==',
                            'value' => 'image',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5a5fc4eb5a18d',
                'label' => 'Hero Background Video URL',
                'name' => 'hero_background_video_url',
                'type' => 'text',
                'instructions' => 'Accepts Wistia only. Plays video in the background of the Hero.',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5afcc23c20fec',
                            'operator' => '==',
                            'value' => 'video',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_57ca193ed2613',
                'label' => 'Hero Video Url',
                'name' => 'hero_video_url',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_57ca1953d2614',
                'label' => 'Hero Button Link',
                'name' => 'hero_btn_link',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array(
                'key' => 'field_57ca1969d2615',
                'label' => 'Hero Button Text',
                'name' => 'hero_btn_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                ),
                array(
                    'param' => 'page_template',
                    'operator' => '!=',
                    'value' => 'front-page.php',
                ),
                array(
                    'param' => 'page_template',
                    'operator' => '!=',
                    'value' => 'page-events.php',
                ),
                array(
                    'param' => 'page_template',
                    'operator' => '!=',
                    'value' => 'page-resources-new.php',
                ),
                array(
                    'param' => 'page_template',
                    'operator' => '!=',
                    'value' => 'page-resources.php',
                ),
                array(
                    'param' => 'page_template',
                    'operator' => '!=',
                    'value' => 'page-about.php',
                ),
                array(
                    'param' => 'page_template',
                    'operator' => '!=',
                    'value' => 'page-partners.php',
                ),
                array(
                    'param' => 'page_template',
                    'operator' => '!=',
                    'value' => 'page-app-login.php',
                ),
            ),
        ),
        'menu_order' => 1,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

endif;