<?php if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5db1eab460c9e',
	'title' => 'International Site Specific Options',
	'fields' => array(
		array(
			'key' => 'field_5db1eaf47339f',
			'label' => 'Href Lang Tag',
			'name' => 'href_lang_tag',
			'type' => 'select',
			'instructions' => 'This code will be placed in the head tag just above the GTM tag. Generate tags here: https://www.aleydasolis.com/english/international-seo-tools/hreflang-tags-generator/',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'en-us' => 'United States English',
				'en-gb' => 'United Kingdom English',
				'en-au' => 'Australia English',
				'fr-fr' => 'France French',
				'ja-jp' => 'Japan Japanese',
				'zh-cn' => 'China Chinese',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5db1ead07339c',
			'label' => 'GTM / Drift Code',
			'name' => 'drift_code',
			'type' => 'textarea',
			'instructions' => 'This code will be placed in the head tag',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5db1f1d6ac9fe',
			'label' => 'Drift Async Code',
			'name' => 'async_drift_code',
			'type' => 'textarea',
			'instructions' => 'This code will be placed in the head tag below the GTM tag',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 25,
			'new_lines' => '',
		),
		array(
			'key' => 'field_5db1eae47339e',
			'label' => 'Custom CSS Code',
			'name' => 'css_code',
			'type' => 'textarea',
			'instructions' => 'This code will be placed in the head tag just above the close head tag',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5db1f1c2979fd',
			'label' => 'Bugherd Code',
			'name' => 'bugherd_code',
			'type' => 'textarea',
			'instructions' => 'This code will be placed in the head tag just above the close head tag',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'This code will be placed in the head tag just above the close head tag',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5db1f2274835a',
			'label' => 'GTM Body Code',
			'name' => 'gtm_body_code',
			'type' => 'textarea',
			'instructions' => 'This code will be placed in the body tag',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-general-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif; ?>