<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_57ca0db1c54ee',
	'title' => 'People Based Marketing',
	'fields' => array(
		array(
			'key' => 'field_57ca0e075937f',
			'label' => 'Partner Text',
			'name' => 'partner_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_57ca127059380',
			'label' => 'Partners Header',
			'name' => 'partners_header',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_57ca127b59381',
			'label' => 'Partners',
			'name' => 'partners',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Row',
			'sub_fields' => array(
				array(
					'key' => 'field_57ca128659382',
					'label' => 'Logo',
					'name' => 'logo',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
		array(
			'key' => 'field_57ca12ae59383',
			'label' => 'Resource List Title',
			'name' => 'resource_list_title',
			'type' => 'text',
			'instructions' => '',
			'required' => '',
			'conditional_logic' => '',
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_57ca0dd95937e',
			'label' => 'Sections',
			'name' => 'sections',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Row',
			'sub_fields' => array(
				array(
					'key' => 'field_57cee75a78ffe',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => '',
					'conditional_logic' => '',
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_57ca136128e7f',
					'label' => 'Header Title',
					'name' => 'header_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_593064c1a2f3c',
					'label' => 'Anchor Link ID',
					'name' => 'anchor_link_id',
					'type' => 'text',
					'instructions' => 'This must be in a URL format e.g.
this-is-the-link-name

Or will be converted to URL format on page load. Defaults to #tab-{number}',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_57ca136b28e80',
					'label' => 'Header Description',
					'name' => 'header_description',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array(
					'key' => 'field_57ca14cb7578a',
					'label' => 'Stages',
					'name' => 'stages',
					'type' => 'repeater',
					'instructions' => '',
					'required' => '',
					'conditional_logic' => '',
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'row',
					'button_label' => 'Add Row',
					'sub_fields' => array(
						array(
							'key' => 'field_57ca14d67578b',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array(
							'key' => 'field_57ca15967578c',
							'label' => 'Description',
							'name' => 'description',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
				),
				array(
					'key' => 'field_57ca15c07578d',
					'label' => 'Benefits',
					'name' => 'benefits',
					'type' => 'repeater',
					'instructions' => '',
					'required' => '',
					'conditional_logic' => '',
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'row',
					'button_label' => 'Add Row',
					'sub_fields' => array(
						array(
							'key' => 'field_57ca15ca7578e',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array(
							'key' => 'field_57e312767e6da',
							'label' => 'Icon',
							'name' => 'icon',
							'type' => 'select',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Audience Agencies' => 'Audience Agencies',
								'Audience Brands' => 'Audience Brands',
								'Audience Data Owners' => 'Audience Data Owners',
								'Audience Platforms' => 'Audience Platforms',
								'Audience Publishers' => 'Audience Publishers',
								'Audience' => 'Audience',
								'Age' => 'Age',
								'3rd Party Data' => '3rd Party Data',
								'Activate' => 'Activate',
								'Activate White Thin' => 'Activate White Thin',
								'Ad Suppression' => 'Ad Suppression',
								'Agency' => 'Agency',
								'Agencies' => 'Agencies',
								'Agency White' => 'Agency White',
								'Analysis' => 'Analysis',
								'Attribution' => 'Attribution',
								'Boost Audience Development' => 'Boost Audience Development',
								'Brand' => 'Brand',
								'Brands' => 'Brands',
								'Brand White' => 'Brand White',
								'Broad Monetization' => 'Broad Monetization',
								'Calendar' => 'Calendar',
								'Capture PBM Budgets' => 'Capture PBM Budgets',
								'Closed Loop Measurement' => 'Closed Loop Measurement',
								'Cogs' => 'Cogs',
								'Connected Data Sources' => 'Connected Data Sources',
								'Console Controller' => 'Console Controller',
								'Consumer Retail' => 'Consumer Retail',
								'Control Limited' => 'Control Limited',
								'Crm Retargeting' => 'Crm Retargeting',
								'Customer Data' => 'Customer Data',
								'Data Connectivity' => 'Data Connectivity',
								'Data Governance' => 'Data Governance',
								'Data Monetization 2' => 'Data Monetization 2',
								'Data Monetization' => 'Data Monetization',
								'Data Movement Out' => 'Data Movement Out',
								'Data Owners' => 'Data Owners',
								'Data' => 'Data',
								'Data Security' => 'Data Security',
								'Data Services' => 'Data Services',
								'Data Ecosystem' => 'Data Ecosystem',
								'Data Sharing' => 'Data Sharing',
								'Data Store' => 'Data Store',
								'Data Syncing' => 'Data Syncing',
								'Disconnected Data Sources' => 'Disconnected Data Sources',
								'Distribute' => 'Distribute',
								'Ecommerce' => 'Ecommerce',
								'Education' => 'Education',
								'Email' => 'Email',
								'Finance' => 'Finance',
								'Food' => 'Food',
								'Food Color' => 'Food Color',
								'Headphones' => 'Headphones',
								'High Impact Ads' => 'High Impact Ads',
								'Hotel' => 'Hotel',
								'Id Matching' => 'Id Matching',
								'Identity Resolution' => 'Identity Resolution',
								'Link' => 'Link',
								'Measurement' => 'Measurement',
								'Methodology' => 'Methodology',
								'Mobile' => 'Mobile',
								'Mobile Phone' => 'Mobile Phone',
								'Native Ads' => 'Native Ads',
								'Offline Purchase' => 'Offline Purchase',
								'Online Behavior' => 'Online Behavior',
								'Online Purchase' => 'Online Purchase',
								'Online Offline' => 'Online Offline',
								'Offline Data Matching' => 'Offline Data Matching',
								'Onboard White Thin' => 'Onboard White Thin',
								'Onboard' => 'Onboard',
								'Omnichannel Advertising' => 'Omnichannel Advertising',
								'Personalization' => 'Personalization',
								'Platform White' => 'Platform White',
								'Platform' => 'Platform',
								'Platforms' => 'Platforms',
								'Platforms Integration' => 'Platforms Integration',
								'Precision' => 'Precision',
								'Private Trust' => 'Private Trust',
								'Publisher' => 'Publisher',
								'Publishers' => 'Publishers',
								'Publisher Data' => 'Publisher Data',
								'Recognized User' => 'Recognized User',
								'Responsive' => 'Responsive',
								'Report' => 'Report',
								'Search' => 'Search',
								'Smart Watch' => 'Smart Watch',
								'Smart Reach' => 'Smart Reach',
								'Strategic Client' => 'Strategic Client',
								'Targeting' => 'Targeting',
								'T Shirt' => 'T Shirt',
								'Tv Set' => 'Tv Set',
								'Gen Temp One' => 'Gen Temp One',
								'Gen Temp Four' => 'Gen Temp Four',
								'Unlock Competitive Advantage' => 'Unlock Competitive Advantage',
								'Contract' => 'Contract',
								'Do It Fast' => 'Do It Fast',
								'Connect Data' => 'Connect Data',
								'Optimize Without Login' => 'Optimize Without Login',
								'Reduce Waste Save Money' => 'Reduce Waste Save Money',
								'White Glove Service' => 'White Glove Service',
								'Maintain Gold Standard' => 'Maintain Gold Standard',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'disabled' => 0,
							'readonly' => 0,
							'return_format' => 'value',
						),
						array(
							'key' => 'field_57ca15d37578f',
							'label' => 'Description',
							'name' => 'description',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
				),
				array(
					'key' => 'field_57e2d4378b187',
					'label' => 'Resource Links Title',
					'name' => 'links_title',
					'type' => 'text',
					'instructions' => '',
					'required' => '',
					'conditional_logic' => '',
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_57ca174c75790',
					'label' => 'Resource Links',
					'name' => 'resource_links',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => 'Add Row',
					'sub_fields' => array(
						array(
							'key' => 'field_57ca179175791',
							'label' => 'Icon',
							'name' => 'nucleo_icon',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'arrows-2_small-left' => 'arrows-2_small-left',
								'files_single-paragraph' => 'files_single-paragraph',
								'files_image' => 'files_image',
								'arrows-1_minimal-down' => 'arrows-1_minimal-down',
								'arrows-3_small-down' => 'arrows-3_small-down',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'disabled' => 0,
							'readonly' => 0,
							'return_format' => 'value',
						),
						array(
							'key' => 'field_57fd672440b9a',
							'label' => 'Resource Link',
							'name' => 'resource_link',
							'type' => 'post_object',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'resources',
								1 => 'resource_link',
								2 => 'blog',
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						),
					),
				),
			),
		),
		array(
			'key' => 'field_57e33696d1ded',
			'label' => 'CTA Title',
			'name' => 'cta_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_57e336c8d1dee',
			'label' => 'CTA Links',
			'name' => 'cta_links',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Row',
			'sub_fields' => array(
				array(
					'key' => 'field_57e336e3d1df0',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_57e336ecd1df1',
					'label' => 'Button Link',
					'name' => 'btn_link',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
					),
					'taxonomy' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'allow_archives' => 1,
				),
				array(
					'key' => 'field_57e3370dd1df2',
					'label' => 'Button Text',
					'name' => 'btn_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-people-marketing.php',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
?>